# Generated by Django 3.1.2 on 2020-10-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField(help_text='latitude of squirrel', max_length=255)),
                ('Longitude', models.FloatField(help_text='longtitude of squirrel', max_length=255)),
                ('Unique_Squirrel_ID', models.CharField(help_text='unique squirrel id', max_length=255, unique=True)),
                ('Shift', models.CharField(help_text='shift of squirrel', max_length=255)),
                ('Date', models.CharField(blank=True, help_text='date', max_length=255)),
                ('Age', models.CharField(blank=True, help_text='age of squirrel', max_length=100)),
                ('Primary_Fur_Color', models.CharField(blank=True, help_text='primary fur color of squirrel', max_length=255)),
                ('Location', models.CharField(blank=True, help_text='location of squirrel', max_length=255)),
                ('Specific_Location', models.CharField(blank=True, help_text='specific location of squirrel', max_length=255)),
                ('Running', models.BooleanField(blank=True, help_text='whether or not squirrel is running')),
                ('Chasing', models.BooleanField(blank=True, help_text='whether or not squirrel is squirrel')),
                ('Climbing', models.BooleanField(blank=True, help_text='whether or not squirrel is climbing')),
                ('Eating', models.BooleanField(blank=True, help_text='whether or not squirrel is eating')),
                ('Foraging', models.BooleanField(blank=True, help_text='whether or not squirrel is foraging')),
                ('Other_Activities', models.CharField(blank=True, help_text='other activities of squirrel', max_length=255)),
                ('Kuks', models.BooleanField(blank=True, help_text='whether or not squirrel kuks')),
                ('Quaas', models.BooleanField(blank=True, help_text='whether or not squirrel quaas')),
                ('Moans', models.BooleanField(blank=True, help_text='whether or not squirrel moans')),
                ('Tail_Flags', models.BooleanField(blank=True, help_text='whether or not squirrel tail flags')),
                ('Tail_Twitches', models.BooleanField(blank=True, help_text='whether or not squirrel tail twitches')),
                ('Approaches', models.BooleanField(blank=True, help_text='whether or not squirrel approaches')),
                ('Indifferent', models.BooleanField(blank=True, help_text='whether or not squirrel is indifferent')),
                ('Runs_From', models.BooleanField(blank=True, help_text='whether or not squirrel runs from')),
            ],
        ),
    ]
